User.create(name: "Bob", email: "bob@email.com", password: "pass")
User.create(name: "Mark", email: "mark@email.com", password: "pass")
User.create(name: "Sam", email: "sam@email.com", password: "pass")
User.create(name: "Dude", email: "dude@email.com", password: "pass")
User.create(name: "NotDude", email: "notdude@email.com", password: "pass")